### PR TITLE
Fixed bar with search result

### PR DESCRIPTION
**Pull request by tkosamja**
https://s1.postimg.org/9qrghrbb9r/Screenshot_from_2017-10-10_17-37-16.png

### CODE REVIEW

**Comment by RaitaroH** [comment]
I don't officially "support" that version of duckduckgo. You see, duckduckgo has a non-javascript version. I am not sure why you are redirected to it though. Maybe NoScript or something like that?
I will make the required fixes asap.

**Comment by RaitaroH** [comment]
You know you can drag-and-drop images right into the comments here, right?

So I fixed what you mentioned:
screenshot from 2017-10-11 14 22 59

I cannot just allow the pull request due to it replacing the user colors with the deepdark colors and having the fixes made in a different way than my own code style. Also the colors are actual hex colors, instead of the variables I use. So yeah, I just had to theme theme it myself :P

Anyway, thanks for the bug report.

**Comment by RaitaroH** [comment]
You can still comment here though, if you want to.

**Comment by tkosamja** [comment]
I see. I am redirected to the non-javascript version since I use NoScript, but still. I see that I changed the user colors, I forgot about that but you just need to add the bottom code. 
Thanks for the reply!

**Comment by RaitaroH** [comment]
Just allow duckduckgo.com in NoScript and you'll be switched to the default duckduckgo page.
If you find other bugs with my themes please let me know.

**Pull request closed without merging**
